server:
  port: 9098

spring:
  data:
    mongodb:
      host: localhost
      port: 27010
      username: voco_task
      password: root
      database: vocoTask
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: 123456789
#  kafka:
#    producer:
#      bootstrap-servers: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      properties:
#        spring:
#          json:
#            type:
#              mapping: KafkaModel = com.voco_task.kafkamq.KafkaModel
#
#    consumer:
#      bootstrap-servers: localhost:9092
#      group-id: group-id
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      properties:
#        spring:
#          json:
#            type:
#              mapping: KafkaModel = com.voco_task.kafkamq.KafkaModel
#          deserializer:
#            value:
#              delegate:
#                class: org.springframework.kafka.support.serializer.JsonDeserializer

#  kafka:
#    producer:
#      bootstrap-servers: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    consumer:
#      bootstrap-servers: localhost:9092
#      group-id: group-id
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

jwt:
  secretKey: ${secretKey}
  issuer: ${issuer}

